// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbkvwmkdifzuawomdhbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxia3Z3bWtkaWZ6dWF3b21kaGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDEzMTcsImV4cCI6MjA2MTI3NzMxN30.3-TVy6UqeQwaHFg5NoUENDfC7C01IIufufpFs_L1xAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);